# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBxI3eFu8cv23VL7mVQHmxu_N-G9WASe
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile verify.sql
# 
# -- BigBasket Capstone - Database Verification
# 
# -- Products count
# SELECT COUNT(*) AS total_products
# FROM products;
# -- Expected: 31
# 
# -- Customers count
# SELECT COUNT(*) AS total_customers
# FROM customers;
# -- Expected: 50
# 
# -- Orders count
# SELECT COUNT(*) AS total_orders
# FROM orders;
# -- Expected: 500
# 
# -- Category targets count
# SELECT COUNT(*) AS total_category_targets
# FROM category_targets;
# -- Expected: 6
# 
# -- Orders by status
# SELECT
#     status,
#     COUNT(*) AS total_orders
# FROM orders
# GROUP BY status
# ORDER BY status;
# -- Expected:
# -- Cancelled = 42
# -- Delivered = 434
# -- Pending = 24

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 01_foundations.sql
# 
# -- ============================================
# -- BigBasket Capstone - Part 1
# -- 01_foundations.sql
# -- ============================================
# 
# 
# -- 1. SELECT + WHERE
# -- Find orders from customers in Mumbai
# 
# SELECT
#     o.order_id,
#     o.customer_id,
#     o.product_id,
#     o.order_date,
#     o.amount_inr,
#     o.status
# FROM orders AS o
# INNER JOIN customers AS c
#     ON o.customer_id = c.customer_id
# WHERE c.city = 'Mumbai';
# 
# 
# -- 2. DISTINCT
# -- List every distinct product category
# 
# SELECT DISTINCT category
# FROM products
# ORDER BY category;
# 
# 
# -- 3. ORDER BY + LIMIT
# -- Find the 5 highest-value orders
# 
# SELECT
#     order_id,
#     customer_id,
#     product_id,
#     amount_inr
# FROM orders
# ORDER BY amount_inr DESC
# LIMIT 5;
# 
# 
# -- 4. ALIAS (AS)
# -- Count total orders and give the result a readable alias
# 
# SELECT
#     COUNT(*) AS total_orders
# FROM orders;
# 
# 
# -- 5. IN
# -- Find orders paid using UPI or Credit Card
# 
# SELECT
#     order_id,
#     payment_mode,
#     amount_inr,
#     status
# FROM orders
# WHERE payment_mode IN ('UPI', 'Credit Card');
# 
# 
# -- 6. BETWEEN
# -- Find orders with amount between INR 100 and INR 500
# 
# SELECT
#     order_id,
#     amount_inr
# FROM orders
# WHERE amount_inr BETWEEN 100 AND 500;
# 
# 
# -- 7. NOT BETWEEN
# -- Find orders outside the INR 100 to INR 500 range
# 
# SELECT
#     order_id,
#     amount_inr
# FROM orders
# WHERE amount_inr NOT BETWEEN 100 AND 500;
# 
# 
# -- 8. IS NULL
# -- Find orders where no rating was recorded
# 
# SELECT
#     order_id,
#     status,
#     rating
# FROM orders
# WHERE rating IS NULL;

import sqlite3

conn = sqlite3.connect("bigbasket_capstone.db")

with open("01_foundations.sql", "r") as f:
    sql = f.read()

print("01_foundations.sql loaded successfully.")
print("Number of SQL statements:", sql.count(";"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 02_aggregation_joins.sql
# 
# -- ============================================
# -- BigBasket Capstone - Part 1
# -- 02_aggregation_joins.sql
# -- ============================================
# 
# 
# -- 1. INNER JOIN + GROUP BY + HAVING
# -- Category-level revenue for Delivered orders
# -- Only categories with revenue above INR 10,000 are shown.
# 
# SELECT
#     p.category,
#     COUNT(o.order_id) AS total_orders,
#     SUM(o.amount_inr) AS total_revenue,
#     AVG(o.amount_inr) AS avg_revenue
# FROM orders AS o
# INNER JOIN products AS p
#     ON o.product_id = p.product_id
# WHERE o.status = 'Delivered'
# GROUP BY p.category
# HAVING total_revenue > 10000
# ORDER BY total_revenue DESC;
# 
# 
# -- 2. LEFT JOIN
# -- Count orders for every product, including products
# -- that have never received an order.
# 
# SELECT
#     p.product_id,
#     p.product_name,
#     p.category,
#     COUNT(o.order_id) AS total_orders
# FROM products AS p
# LEFT JOIN orders AS o
#     ON p.product_id = o.product_id
# GROUP BY
#     p.product_id,
#     p.product_name,
#     p.category
# ORDER BY total_orders ASC;

import sqlite3

conn = sqlite3.connect("bigbasket_capstone.db")

with open("02_aggregation_joins.sql", "r") as f:
    sql = f.read()

print("02_aggregation_joins.sql loaded successfully.")
print("Number of SQL statements:", sql.count(";"))

import sqlite3

# Open a fresh connection
conn = sqlite3.connect("bigbasket_capstone.db")

query = """
SELECT
    p.product_name,
    COUNT(o.order_id) AS total_orders
FROM products AS p
LEFT JOIN orders AS o
    ON p.product_id = o.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_orders ASC;
"""

rows = conn.execute(query).fetchall()

print("Total products returned:", len(rows))
print("First 10 results:")

for row in rows[:10]:
    print(row)

import sqlite3
import os

# Make sure the database is freshly generated
!python generate_data.py

# Close any old connection
try:
    conn.close()
except:
    pass

# Connect to the correct database
conn = sqlite3.connect("bigbasket_capstone.db")

# Check what tables actually exist
tables = conn.execute("""
SELECT name
FROM sqlite_master
WHERE type = 'table'
ORDER BY name;
""").fetchall()

print("Tables in database:")
for table in tables:
    print(table[0])

# Commented out IPython magic to ensure Python compatibility.
# %%writefile generate_data.py
# 
# import sqlite3, random, csv
# from datetime import date, timedelta
# 
# random.seed(42)
# 
# conn = sqlite3.connect("bigbasket_capstone.db")
# cur = conn.cursor()
# 
# cur.executescript("""
# DROP TABLE IF EXISTS products;
# DROP TABLE IF EXISTS customers;
# DROP TABLE IF EXISTS orders;
# DROP TABLE IF EXISTS category_targets;
# 
# CREATE TABLE products (
#     product_id INTEGER PRIMARY KEY,
#     product_name TEXT NOT NULL,
#     category TEXT NOT NULL,
#     supplier TEXT NOT NULL,
#     unit_price_inr INTEGER NOT NULL
# );
# 
# CREATE TABLE customers (
#     customer_id INTEGER PRIMARY KEY,
#     name TEXT NOT NULL,
#     signup_date TEXT NOT NULL,
#     city TEXT NOT NULL
# );
# 
# CREATE TABLE orders (
#     order_id INTEGER PRIMARY KEY,
#     customer_id INTEGER NOT NULL,
#     product_id INTEGER NOT NULL,
#     order_date TEXT NOT NULL,
#     quantity INTEGER NOT NULL,
#     amount_inr INTEGER NOT NULL,
#     payment_mode TEXT NOT NULL,
#     status TEXT NOT NULL,
#     rating INTEGER,
#     FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
#     FOREIGN KEY (product_id) REFERENCES products(product_id)
# );
# 
# CREATE TABLE category_targets (
#     category TEXT PRIMARY KEY,
#     target_revenue_inr INTEGER NOT NULL
# );
# """)
# 
# cities = ["Bengaluru", "Mumbai", "Hyderabad", "Pune"]
# 
# products_raw = [
#     ("Banana 1kg", "Fruits & Vegetables", "FreshFarms Co", 50),
#     ("Tomato 1kg", "Fruits & Vegetables", "FreshFarms Co", 40),
#     ("Onion 1kg", "Fruits & Vegetables", "GreenValley Traders", 35),
#     ("Apple 1kg", "Fruits & Vegetables", "GreenValley Traders", 180),
#     ("Spinach Bunch", "Fruits & Vegetables", "FreshFarms Co", 25),
#     ("Toned Milk 1L", "Dairy & Eggs", "DairyBest Ltd", 60),
#     ("Paneer 200g", "Dairy & Eggs", "DairyBest Ltd", 90),
#     ("Eggs (12pc)", "Dairy & Eggs", "CountryEggs Farms", 84),
#     ("Curd 400g", "Dairy & Eggs", "DairyBest Ltd", 45),
#     ("Butter 100g", "Dairy & Eggs", "CountryEggs Farms", 55),
#     ("Potato Chips 90g", "Snacks & Beverages", "SnackHub India", 30),
#     ("Cola 750ml", "Snacks & Beverages", "SnackHub India", 45),
#     ("Biscuit Pack", "Snacks & Beverages", "BakeHouse Supplies", 35),
#     ("Fruit Juice 1L", "Snacks & Beverages", "SnackHub India", 110),
#     ("Namkeen 200g", "Snacks & Beverages", "BakeHouse Supplies", 60),
#     ("Shampoo 340ml", "Personal Care", "CarePlus Distributors", 220),
#     ("Toothpaste 150g", "Personal Care", "CarePlus Distributors", 95),
#     ("Soap Bar 125g", "Personal Care", "CarePlus Distributors", 40),
#     ("Hand Wash 250ml", "Personal Care", "CarePlus Distributors", 99),
#     ("Face Wash 100g", "Personal Care", "CarePlus Distributors", 150),
#     ("Dish Wash Bar", "Household Essentials", "HomeEssentials Traders", 20),
#     ("Detergent 1kg", "Household Essentials", "HomeEssentials Traders", 130),
#     ("Floor Cleaner 1L", "Household Essentials", "HomeEssentials Traders", 145),
#     ("Toilet Cleaner 500ml", "Household Essentials", "HomeEssentials Traders", 89),
#     ("Garbage Bags (30pc)", "Household Essentials", "HomeEssentials Traders", 75),
#     ("Bread Loaf", "Bakery", "BakeHouse Supplies", 45),
#     ("Croissant (2pc)", "Bakery", "BakeHouse Supplies", 70),
#     ("Muffin Pack (4pc)", "Bakery", "BakeHouse Supplies", 120),
#     ("Cake Slice", "Bakery", "BakeHouse Supplies", 85),
#     ("Cookies 200g", "Bakery", "BakeHouse Supplies", 65),
#     ("Premium Face Cream 50g", "Personal Care", "CarePlus Distributors", 450),
# ]
# 
# products = [(i, *p) for i, p in enumerate(products_raw, start=1)]
# cur.executemany("INSERT INTO products VALUES (?,?,?,?,?)", products)
# 
# first_names = [
#     "Aarav","Vivaan","Aditya","Vihaan","Arjun","Sai","Reyansh","Ayaan",
#     "Krishna","Ishaan","Ananya","Diya","Saanvi","Aadhya","Kiara","Myra",
#     "Anika","Navya","Riya","Siya","Rohan","Kabir","Dev","Yash","Aryan",
#     "Zara","Meera","Tara","Nisha","Priya","Aman","Rahul","Karan","Varun",
#     "Nikhil","Pooja","Neha","Simran","Divya","Isha","Rohit","Sanjay",
#     "Vikram","Manish","Deepak","Kavya","Shreya","Anjali","Pallavi","Sneha"
# ]
# 
# customers = []
# start_signup = date(2025, 1, 1)
# 
# for i, fname in enumerate(first_names, start=1):
#     city = cities[i % len(cities)]
#     signup = start_signup + timedelta(days=random.randint(0, 400))
#     customers.append((i, fname, signup.isoformat(), city))
# 
# cur.executemany("INSERT INTO customers VALUES (?,?,?,?)", customers)
# 
# popularity_weights = [
#     10,8,6,3,5,
#     9,7,6,8,4,
#     10,9,5,4,6,
#     3,5,9,4,3,
#     8,6,5,4,7,
#     6,4,3,5,4
# ]
# 
# order_date_start = date(2026, 1, 1)
# order_date_end = date(2026, 6, 30)
# total_days = (order_date_end - order_date_start).days
# 
# TOTAL_ORDERS = 500
# 
# product_ids_weighted = []
# 
# for pid, w in zip(range(1, 31), popularity_weights):
#     product_ids_weighted.extend([pid] * w)
# 
# payment_modes = [
#     "UPI",
#     "Credit Card",
#     "Debit Card",
#     "Cash on Delivery",
#     "Wallet"
# ]
# 
# product_lookup = {p[0]: p for p in products}
# customer_lookup = {c[0]: c for c in customers}
# 
# orders = []
# order_id = 1
# 
# for _ in range(TOTAL_ORDERS):
# 
#     cust_id = random.randint(1, 50)
#     prod_id = random.choice(product_ids_weighted)
# 
#     unit_price = product_lookup[prod_id][4]
#     quantity = random.randint(1, 5)
#     amount = quantity * unit_price
# 
#     day_offset = random.randint(0, total_days)
#     o_date = order_date_start + timedelta(days=day_offset)
# 
#     payment_mode = random.choice(payment_modes)
# 
#     roll = random.random()
# 
#     if roll < 0.85:
#         status = "Delivered"
#         rating = random.randint(1, 5)
#     elif roll < 0.95:
#         status = "Cancelled"
#         rating = None
#     else:
#         status = "Pending"
#         rating = None
# 
#     orders.append([
#         order_id,
#         cust_id,
#         prod_id,
#         o_date.isoformat(),
#         quantity,
#         amount,
#         payment_mode,
#         status,
#         rating
#     ])
# 
#     order_id += 1
# 
# cur.executemany(
#     "INSERT INTO orders VALUES (?,?,?,?,?,?,?,?,?)",
#     [tuple(o) for o in orders]
# )
# 
# category_targets = [
#     ("Fruits & Vegetables", 12000),
#     ("Dairy & Eggs", 16500),
#     ("Snacks & Beverages", 13000),
#     ("Personal Care", 15500),
#     ("Household Essentials", 17000),
#     ("Bakery", 12000),
# ]
# 
# cur.executemany(
#     "INSERT INTO category_targets VALUES (?,?)",
#     category_targets
# )
# 
# conn.commit()
# 
# # Raw exports for Part 4
# raw_rows = []
# 
# for o in orders:
# 
#     order_id, cust_id, prod_id, o_date, qty, amt, pm, status, rating = o
#     cust = customer_lookup[cust_id]
# 
#     raw_rows.append({
#         "order_id": order_id,
#         "order_date": o_date,
#         "customer_name": cust[1],
#         "city": cust[3],
#         "category": product_lookup[prod_id][2],
#         "product_id": prod_id,
#         "quantity": qty,
#         "amount_inr": amt,
#         "payment_mode": pm,
#         "status": status,
#         "rating": rating if rating is not None else "",
#     })
# 
# rng2 = random.Random(7)
# 
# casing_idx = rng2.sample(range(len(raw_rows)), 20)
# 
# for idx in casing_idx:
# 
#     r = raw_rows[idx]
# 
#     variant = rng2.choice(["upper", "lower", "space"])
# 
#     r["city"] = (
#         r["city"].upper()
#         if variant == "upper"
#         else (
#             r["city"].lower()
#             if variant == "lower"
#             else " " + r["city"] + " "
#         )
#     )
# 
#     variant2 = rng2.choice(["upper", "lower", "space"])
# 
#     r["category"] = (
#         r["category"].upper()
#         if variant2 == "upper"
#         else (
#             r["category"].lower()
#             if variant2 == "lower"
#             else " " + r["category"] + " "
#         )
#     )
# 
# null_idx = rng2.sample(
#     [i for i in range(len(raw_rows)) if i not in casing_idx],
#     10
# )
# 
# for idx in null_idx:
#     raw_rows[idx]["amount_inr"] = ""
# 
# outlier_pool = [
#     i for i in range(len(raw_rows))
#     if i not in casing_idx and i not in null_idx
# ]
# 
# outlier_idx = rng2.sample(outlier_pool, 5)
# 
# for idx in outlier_idx:
#     raw_rows[idx]["amount_inr"] = raw_rows[idx]["amount_inr"] * 40
# 
# dup_pool = [
#     i for i in range(len(raw_rows))
#     if i not in casing_idx
#     and i not in null_idx
#     and i not in outlier_idx
# ]
# 
# dup_idx = rng2.sample(dup_pool, 8)
# 
# all_rows = raw_rows + [dict(raw_rows[i]) for i in dup_idx]
# 
# fieldnames = [
#     "order_id",
#     "order_date",
#     "customer_name",
#     "city",
#     "category",
#     "product_id",
#     "quantity",
#     "amount_inr",
#     "payment_mode",
#     "status",
#     "rating"
# ]
# 
# with open("orders_raw.csv", "w", newline="") as f:
# 
#     w = csv.DictWriter(f, fieldnames=fieldnames)
# 
#     w.writeheader()
#     w.writerows(all_rows)
# 
# with open("products.csv", "w", newline="") as f:
# 
#     w = csv.writer(f)
# 
#     w.writerow([
#         "product_id",
#         "product_name",
#         "category",
#         "supplier",
#         "unit_price_inr"
#     ])
# 
#     w.writerows(products)
# 
# conn.close()
# 
# print("bigbasket_capstone.db, orders_raw.csv, products.csv created.")

import sqlite3

conn = sqlite3.connect("bigbasket_capstone.db")

print("Products:", conn.execute("SELECT COUNT(*) FROM products").fetchone()[0])
print("Customers:", conn.execute("SELECT COUNT(*) FROM customers").fetchone()[0])
print("Orders:", conn.execute("SELECT COUNT(*) FROM orders").fetchone()[0])
print("Category targets:", conn.execute("SELECT COUNT(*) FROM category_targets").fetchone()[0])

!python generate_data.py

import sqlite3

conn = sqlite3.connect("bigbasket_capstone.db")

print("Products:", conn.execute("SELECT COUNT(*) FROM products").fetchone()[0])
print("Customers:", conn.execute("SELECT COUNT(*) FROM customers").fetchone()[0])
print("Orders:", conn.execute("SELECT COUNT(*) FROM orders").fetchone()[0])
print("Category targets:", conn.execute("SELECT COUNT(*) FROM category_targets").fetchone()[0])

conn.execute("""
SELECT status, COUNT(*) AS total_orders
FROM orders
GROUP BY status
ORDER BY status;
""").fetchall()

!python generate_data.py

import sqlite3

conn = sqlite3.connect("bigbasket_capstone.db")

query = """
SELECT
    p.product_name,
    COUNT(o.order_id) AS total_orders
FROM products AS p
LEFT JOIN orders AS o
    ON p.product_id = o.product_id
GROUP BY
    p.product_id,
    p.product_name
ORDER BY total_orders ASC;
"""

rows = conn.execute(query).fetchall()

print("Total products returned:", len(rows))
print("\nFirst 10 products:")

for row in rows[:10]:
    print(row)

zero_orders = conn.execute("""
SELECT
    p.product_name,
    COUNT(o.order_id) AS total_orders
FROM products AS p
LEFT JOIN orders AS o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name
HAVING COUNT(o.order_id) = 0;
""").fetchall()

print(zero_orders)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 03_reporting.sql
# 
# -- ============================================
# -- BigBasket Capstone - Part 1
# -- 03_reporting.sql
# -- ============================================
# 
# 
# -- 1. CASE WHEN PRODUCT REVENUE TIERING
# -- Tier each product based on total Delivered revenue.
# 
# SELECT
#     p.product_id,
#     p.product_name,
#     p.category,
#     SUM(o.amount_inr) AS total_revenue,
#     CASE
#         WHEN SUM(o.amount_inr) >= 3000 THEN 'High'
#         WHEN SUM(o.amount_inr) >= 1000 THEN 'Medium'
#         ELSE 'Low'
#     END AS revenue_tier
# FROM products AS p
# INNER JOIN orders AS o
#     ON p.product_id = o.product_id
# WHERE o.status = 'Delivered'
# GROUP BY
#     p.product_id,
#     p.product_name,
#     p.category
# ORDER BY total_revenue DESC;
# 
# 
# -- 2. MONTHLY-BY-CATEGORY BUSINESS REPORT
# -- This is the query used to create monthly_category_revenue.csv.
# 
# SELECT
#     p.category AS category,
#     strftime('%Y-%m', o.order_date) AS month,
#     COUNT(o.order_id) AS order_count,
#     SUM(o.amount_inr) AS total_revenue,
#     AVG(o.amount_inr) AS avg_revenue
# FROM orders AS o
# INNER JOIN products AS p
#     ON o.product_id = p.product_id
# WHERE o.status = 'Delivered'
# GROUP BY
#     p.category,
#     strftime('%Y-%m', o.order_date)
# ORDER BY
#     p.category,
#     month;
# 
# 
# -- 3. CATEGORY TARGET VARIANCE REPORT
# -- Compare category revenue against category targets.
# 
# SELECT
#     p.category,
#     SUM(o.amount_inr) AS total_revenue,
#     ct.target_revenue_inr,
# 
#     ct.target_revenue_inr - SUM(o.amount_inr)
#         AS variance,
# 
#     ((SUM(o.amount_inr) - ct.target_revenue_inr) * 100.0)
#         / ct.target_revenue_inr
#         AS percentage_variance,
# 
#     CASE
#         WHEN SUM(o.amount_inr) >= ct.target_revenue_inr
#             THEN 'Above Target'
# 
#         WHEN (
#             (ct.target_revenue_inr - SUM(o.amount_inr)) * 100.0
#             / ct.target_revenue_inr
#         ) <= 15
#             THEN 'Below Target - Watch'
# 
#         ELSE 'Below Target - Critical'
#     END AS target_status
# 
# FROM orders AS o
# 
# INNER JOIN products AS p
#     ON o.product_id = p.product_id
# 
# INNER JOIN category_targets AS ct
#     ON p.category = ct.category
# 
# WHERE o.status = 'Delivered'
# 
# GROUP BY
#     p.category,
#     ct.target_revenue_inr
# 
# ORDER BY total_revenue DESC;

with open("03_reporting.sql", "r") as f:
    sql = f.read()

print("03_reporting.sql loaded successfully.")
print("Number of SQL statements:", sql.count(";"))

monthly_query = """
SELECT
    p.category AS category,
    strftime('%Y-%m', o.order_date) AS month,
    COUNT(o.order_id) AS order_count,
    SUM(o.amount_inr) AS total_revenue,
    AVG(o.amount_inr) AS avg_revenue
FROM orders AS o
INNER JOIN products AS p
    ON o.product_id = p.product_id
WHERE o.status = 'Delivered'
GROUP BY
    p.category,
    strftime('%Y-%m', o.order_date)
ORDER BY
    p.category,
    month;
"""

monthly_df = pd.read_sql_query(monthly_query, conn)

print("Rows:", len(monthly_df))
print("Columns:", list(monthly_df.columns))
print("Grand total revenue:", monthly_df["total_revenue"].sum())

import pandas as pd

monthly_df = pd.read_sql_query(monthly_query, conn)

print("Rows:", len(monthly_df))
print("Columns:", list(monthly_df.columns))
print("Grand total revenue:", monthly_df["total_revenue"].sum())

monthly_df.to_csv("monthly_category_revenue.csv", index=False)

print("monthly_category_revenue.csv created successfully.")

category_check = pd.read_sql_query("""
SELECT
    p.category,
    SUM(o.amount_inr) AS total_revenue
FROM orders AS o
JOIN products AS p
    ON o.product_id = p.product_id
WHERE o.status = 'Delivered'
GROUP BY p.category
ORDER BY total_revenue DESC;
""", conn)

category_check

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ai_log.md
# 
# # AI-Assisted Prompting Log
# 
# ## Prompt 1 — SQL Debugging / Reporting
# 
# ### Role
# Act as a SQL analyst experienced with SQLite and retail/e-commerce reporting.
# 
# ### Context
# I am completing a BigBasket category performance diagnostic using a deterministic SQLite database containing products, customers, orders, and category revenue targets. The database contains 500 orders from January through June 2026. I need to create a monthly revenue-by-category report using only Delivered orders.
# 
# ### Task
# Help me write or debug a SQLite SQL query that joins the orders table with the products table, groups the results by product category and month, calculates order_count, total_revenue, and avg_revenue, and extracts the month using SQLite's strftime() function.
# 
# ### Constraints
# Use SQLite syntax. Only include Delivered orders. Use strftime('%Y-%m', order_date) for the month. Do not modify the underlying database. The output must contain exactly these five columns: category, month, order_count, total_revenue, avg_revenue.
# 
# ### Format
# Return one runnable SQL query in a code block, followed by a short explanation of the joins, filtering, grouping, and date extraction.
# 
# ### Verification performed
# I ran the suggested SQL query against bigbasket_capstone.db in Google Colab and verified that it returned exactly 36 rows, contained the five required columns, and produced a grand total Delivered revenue of INR 88,282. I also compared the category totals with the expected Part 1 SQL results.

with open("ai_log.md", "r") as f:
    print(f.read())

from google.colab import files

files.download("monthly_category_revenue.csv")

import os

files = [
    "generate_data.py",
    "bigbasket_capstone.db",
    "orders_raw.csv",
    "products.csv",
    "verify.sql",
    "01_foundations.sql",
    "02_aggregation_joins.sql",
    "03_reporting.sql",
    "monthly_category_revenue.csv",
    "ai_log.md"
]

for f in files:
    print("✅" if os.path.exists(f) else "❌", f)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile generate_data.py
# import sqlite3, random, csv
# from datetime import date, timedelta
# 
# random.seed(42)
# 
# conn = sqlite3.connect("bigbasket_capstone.db")
# cur = conn.cursor()
# 
# cur.executescript("""
# DROP TABLE IF EXISTS products;
# DROP TABLE IF EXISTS customers;
# DROP TABLE IF EXISTS orders;
# DROP TABLE IF EXISTS category_targets;
# 
# CREATE TABLE products (
#     product_id INTEGER PRIMARY KEY,
#     product_name TEXT NOT NULL,
#     category TEXT NOT NULL,
#     supplier TEXT NOT NULL,
#     unit_price_inr INTEGER NOT NULL
# );
# 
# CREATE TABLE customers (
#     customer_id INTEGER PRIMARY KEY,
#     name TEXT NOT NULL,
#     signup_date TEXT NOT NULL,
#     city TEXT NOT NULL
# );
# 
# CREATE TABLE orders (
#     order_id INTEGER PRIMARY KEY,
#     customer_id INTEGER NOT NULL,
#     product_id INTEGER NOT NULL,
#     order_date TEXT NOT NULL,
#     quantity INTEGER NOT NULL,
#     amount_inr INTEGER NOT NULL,
#     payment_mode TEXT NOT NULL,
#     status TEXT NOT NULL,
#     rating INTEGER,
#     FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
#     FOREIGN KEY (product_id) REFERENCES products(product_id)
# );
# 
# CREATE TABLE category_targets (
#     category TEXT PRIMARY KEY,
#     target_revenue_inr INTEGER NOT NULL
# );
# """)
# 
# cities = ["Bengaluru", "Mumbai", "Hyderabad", "Pune"]
# 
# products_raw = [
#     ("Banana 1kg", "Fruits & Vegetables", "FreshFarms Co", 50),
#     ("Tomato 1kg", "Fruits & Vegetables", "FreshFarms Co", 40),
#     ("Onion 1kg", "Fruits & Vegetables", "GreenValley Traders", 35),
#     ("Apple 1kg", "Fruits & Vegetables", "GreenValley Traders", 180),
#     ("Spinach Bunch", "Fruits & Vegetables", "FreshFarms Co", 25),
#     ("Toned Milk 1L", "Dairy & Eggs", "DairyBest Ltd", 60),
#     ("Paneer 200g", "Dairy & Eggs", "DairyBest Ltd", 90),
#     ("Eggs (12pc)", "Dairy & Eggs", "CountryEggs Farms", 84),
#     ("Curd 400g", "Dairy & Eggs", "DairyBest Ltd", 45),
#     ("Butter 100g", "Dairy & Eggs", "CountryEggs Farms", 55),
#     ("Potato Chips 90g", "Snacks & Beverages", "SnackHub India", 30),
#     ("Cola 750ml", "Snacks & Beverages", "SnackHub India", 45),
#     ("Biscuit Pack", "Snacks & Beverages", "BakeHouse Supplies", 35),
#     ("Fruit Juice 1L", "Snacks & Beverages", "SnackHub India", 110),
#     ("Namkeen 200g", "Snacks & Beverages", "BakeHouse Supplies", 60),
#     ("Shampoo 340ml", "Personal Care", "CarePlus Distributors", 220),
#     ("Toothpaste 150g", "Personal Care", "CarePlus Distributors", 95),
#     ("Soap Bar 125g", "Personal Care", "CarePlus Distributors", 40),
#     ("Hand Wash 250ml", "Personal Care", "CarePlus Distributors", 99),
#     ("Face Wash 100g", "Personal Care", "CarePlus Distributors", 150),
#     ("Dish Wash Bar", "Household Essentials", "HomeEssentials Traders", 20),
#     ("Detergent 1kg", "Household Essentials", "HomeEssentials Traders", 130),
#     ("Floor Cleaner 1L", "Household Essentials", "HomeEssentials Traders", 145),
#     ("Toilet Cleaner 500ml", "Household Essentials", "HomeEssentials Traders", 89),
#     ("Garbage Bags (30pc)", "Household Essentials", "HomeEssentials Traders", 75),
#     ("Bread Loaf", "Bakery", "BakeHouse Supplies", 45),
#     ("Croissant (2pc)", "Bakery", "BakeHouse Supplies", 70),
#     ("Muffin Pack (4pc)", "Bakery", "BakeHouse Supplies", 120),
#     ("Cake Slice", "Bakery", "BakeHouse Supplies", 85),
#     ("Cookies 200g", "Bakery", "BakeHouse Supplies", 65),
#     ("Premium Face Cream 50g", "Personal Care", "CarePlus Distributors", 450),
# ]
# 
# products = [(i, *p) for i, p in enumerate(products_raw, start=1)]
# cur.executemany("INSERT INTO products VALUES (?,?,?,?,?)", products)
# 
# first_names = [
#     "Aarav","Vivaan","Aditya","Vihaan","Arjun","Sai","Reyansh","Ayaan","Krishna","Ishaan",
#     "Ananya","Diya","Saanvi","Aadhya","Kiara","Myra","Anika","Navya","Riya","Siya",
#     "Rohan","Kabir","Dev","Yash","Aryan","Zara","Meera","Tara","Nisha","Priya",
#     "Aman","Rahul","Karan","Varun","Nikhil","Pooja","Neha","Simran","Divya","Isha",
#     "Rohit","Sanjay","Vikram","Manish","Deepak","Kavya","Shreya","Anjali","Pallavi","Sneha"
# ]
# 
# customers = []
# start_signup = date(2025, 1, 1)
# 
# for i, fname in enumerate(first_names, start=1):
#     city = cities[i % len(cities)]
#     signup = start_signup + timedelta(days=random.randint(0, 400))
#     customers.append((i, fname, signup.isoformat(), city))
# 
# cur.executemany("INSERT INTO customers VALUES (?,?,?,?)", customers)
# 
# popularity_weights = [
#     10,8,6,3,5, 9,7,6,8,4, 10,9,5,4,6,
#     3,5,9,4,3, 8,6,5,4,7, 6,4,3,5,4
# ]
# 
# order_date_start = date(2026, 1, 1)
# order_date_end = date(2026, 6, 30)
# total_days = (order_date_end - order_date_start).days
# 
# product_ids_weighted = []
# 
# for pid, w in zip(range(1, 31), popularity_weights):
#     product_ids_weighted.extend([pid] * w)
# 
# payment_modes = ["UPI", "Credit Card", "Debit Card", "Cash on Delivery", "Wallet"]
# 
# product_lookup = {p[0]: p for p in products}
# customer_lookup = {c[0]: c for c in customers}
# 
# orders = []
# order_id = 1
# 
# for _ in range(500):
#     cust_id = random.randint(1, 50)
#     prod_id = random.choice(product_ids_weighted)
#     unit_price = product_lookup[prod_id][4]
#     quantity = random.randint(1, 5)
#     amount = quantity * unit_price
# 
#     day_offset = random.randint(0, total_days)
#     o_date = order_date_start + timedelta(days=day_offset)
# 
#     payment_mode = random.choice(payment_modes)
#     roll = random.random()
# 
#     if roll < 0.85:
#         status = "Delivered"
#         rating = random.randint(1, 5)
#     elif roll < 0.95:
#         status = "Cancelled"
#         rating = None
#     else:
#         status = "Pending"
#         rating = None
# 
#     orders.append([
#         order_id, cust_id, prod_id, o_date.isoformat(),
#         quantity, amount, payment_mode, status, rating
#     ])
# 
#     order_id += 1
# 
# cur.executemany(
#     "INSERT INTO orders VALUES (?,?,?,?,?,?,?,?,?)",
#     [tuple(o) for o in orders]
# )
# 
# category_targets = [
#     ("Fruits & Vegetables", 12000),
#     ("Dairy & Eggs", 16500),
#     ("Snacks & Beverages", 13000),
#     ("Personal Care", 15500),
#     ("Household Essentials", 17000),
#     ("Bakery", 12000),
# ]
# 
# cur.executemany(
#     "INSERT INTO category_targets VALUES (?,?)",
#     category_targets
# )
# 
# conn.commit()
# 
# # Raw orders export
# raw_rows = []
# 
# for o in orders:
#     order_id, cust_id, prod_id, o_date, qty, amt, pm, status, rating = o
#     cust = customer_lookup[cust_id]
# 
#     raw_rows.append({
#         "order_id": order_id,
#         "order_date": o_date,
#         "customer_name": cust[1],
#         "city": cust[3],
#         "category": product_lookup[prod_id][2],
#         "product_id": prod_id,
#         "quantity": qty,
#         "amount_inr": amt,
#         "payment_mode": pm,
#         "status": status,
#         "rating": rating if rating is not None else "",
#     })
# 
# rng2 = random.Random(7)
# 
# casing_idx = rng2.sample(range(len(raw_rows)), 20)
# 
# for idx in casing_idx:
#     r = raw_rows[idx]
# 
#     variant = rng2.choice(["upper", "lower", "space"])
#     r["city"] = (
#         r["city"].upper()
#         if variant == "upper"
#         else r["city"].lower()
#         if variant == "lower"
#         else " " + r["city"] + " "
#     )
# 
#     variant2 = rng2.choice(["upper", "lower", "space"])
#     r["category"] = (
#         r["category"].upper()
#         if variant2 == "upper"
#         else r["category"].lower()
#         if variant2 == "lower"
#         else " " + r["category"] + " "
#     )
# 
# null_idx = rng2.sample(
#     [i for i in range(len(raw_rows)) if i not in casing_idx], 10
# )
# 
# for idx in null_idx:
#     raw_rows[idx]["amount_inr"] = ""
# 
# outlier_pool = [
#     i for i in range(len(raw_rows))
#     if i not in casing_idx
#     and i not in null_idx
# ]
# 
# outlier_idx = rng2.sample(outlier_pool, 5)
# 
# for idx in outlier_idx:
#     raw_rows[idx]["amount_inr"] = raw_rows[idx]["amount_inr"] * 40
# 
# dup_pool = [
#     i for i in range(len(raw_rows))
#     if i not in casing_idx
#     and i not in null_idx
#     and i not in outlier_idx
# ]
# 
# dup_idx = rng2.sample(dup_pool, 8)
# 
# all_rows = raw_rows + [dict(raw_rows[i]) for i in dup_idx]
# 
# fieldnames = [
#     "order_id","order_date","customer_name","city","category",
#     "product_id","quantity","amount_inr","payment_mode","status","rating"
# ]
# 
# with open("orders_raw.csv", "w", newline="") as f:
#     w = csv.DictWriter(f, fieldnames=fieldnames)
#     w.writeheader()
#     w.writerows(all_rows)
# 
# with open("products.csv", "w", newline="") as f:
#     w = csv.writer(f)
#     w.writerow([
#         "product_id","product_name","category","supplier","unit_price_inr"
#     ])
#     w.writerows(products)
# 
# conn.close()
# 
# print("bigbasket_capstone.db, orders_raw.csv, products.csv created.")

!python generate_data.py

import sqlite3
import pandas as pd

conn = sqlite3.connect("bigbasket_capstone.db")

print("PRODUCTS:", pd.read_sql("SELECT COUNT(*) AS count FROM products", conn).iloc[0,0])
print("CUSTOMERS:", pd.read_sql("SELECT COUNT(*) AS count FROM customers", conn).iloc[0,0])
print("ORDERS:", pd.read_sql("SELECT COUNT(*) AS count FROM orders", conn).iloc[0,0])
print("TARGETS:", pd.read_sql("SELECT COUNT(*) AS count FROM category_targets", conn).iloc[0,0])

print("\nORDER STATUS:")
print(pd.read_sql("""
SELECT status, COUNT(*) AS count
FROM orders
GROUP BY status
ORDER BY status
""", conn))

df = pd.read_csv("orders_raw.csv")
print("\nRAW ORDERS ROWS:", len(df))

conn.close()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 01_foundations.sql
# -- 1. WHERE
# SELECT *
# FROM orders
# WHERE customer_id IN (
#     SELECT customer_id
#     FROM customers
#     WHERE city = 'Mumbai'
# );
# 
# -- 2. DISTINCT
# SELECT DISTINCT category
# FROM products
# ORDER BY category;
# 
# -- 3. ORDER BY + LIMIT
# SELECT order_id, amount_inr
# FROM orders
# ORDER BY amount_inr DESC
# LIMIT 5;
# 
# -- 4. Alias (AS)
# SELECT COUNT(*) AS total_orders
# FROM orders;
# 
# -- 5. IN
# SELECT *
# FROM orders
# WHERE payment_mode IN ('UPI', 'Credit Card');
# 
# -- 6. BETWEEN
# SELECT *
# FROM orders
# WHERE amount_inr BETWEEN 100 AND 500;
# 
# -- 7. NOT BETWEEN
# SELECT *
# FROM orders
# WHERE amount_inr NOT BETWEEN 100 AND 500;
# 
# -- 8. IS NULL
# SELECT *
# FROM orders
# WHERE rating IS NULL;

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 02_aggregation_joins.sql
# 
# -- 1. INNER JOIN + GROUP BY + HAVING
# SELECT
#     p.category,
#     COUNT(o.order_id) AS order_count,
#     SUM(o.amount_inr) AS total_revenue,
#     AVG(o.amount_inr) AS avg_revenue
# FROM orders AS o
# INNER JOIN products AS p
#     ON o.product_id = p.product_id
# WHERE o.status = 'Delivered'
# GROUP BY p.category
# HAVING total_revenue > 10000
# ORDER BY total_revenue DESC;
# 
# 
# -- 2. LEFT JOIN: order count for every product
# SELECT
#     p.product_name,
#     COUNT(o.order_id) AS order_count
# FROM products AS p
# LEFT JOIN orders AS o
#     ON p.product_id = o.product_id
# GROUP BY p.product_id, p.product_name
# ORDER BY order_count ASC, p.product_name;

# Commented out IPython magic to ensure Python compatibility.
# %%writefile 03_reporting.sql
# 
# -- 1. CASE WHEN: Product revenue tiering
# WITH product_revenue AS (
#     SELECT
#         p.product_name,
#         SUM(o.amount_inr) AS total_revenue
#     FROM orders AS o
#     INNER JOIN products AS p
#         ON o.product_id = p.product_id
#     WHERE o.status = 'Delivered'
#     GROUP BY p.product_id, p.product_name
# )
# SELECT
#     product_name,
#     total_revenue,
#     CASE
#         WHEN total_revenue >= 3000 THEN 'High'
#         WHEN total_revenue >= 1000 THEN 'Medium'
#         ELSE 'Low'
#     END AS revenue_tier
# FROM product_revenue
# ORDER BY total_revenue DESC;
# 
# 
# -- 2. Monthly revenue by category
# SELECT
#     p.category AS category,
#     strftime('%Y-%m', o.order_date) AS month,
#     COUNT(o.order_id) AS order_count,
#     SUM(o.amount_inr) AS total_revenue,
#     AVG(o.amount_inr) AS avg_revenue
# FROM orders AS o
# INNER JOIN products AS p
#     ON o.product_id = p.product_id
# WHERE o.status = 'Delivered'
# GROUP BY
#     p.category,
#     strftime('%Y-%m', o.order_date)
# ORDER BY
#     p.category,
#     month;
# 
# 
# -- 3. Category target variance
# WITH category_revenue AS (
#     SELECT
#         p.category,
#         SUM(o.amount_inr) AS total_revenue
#     FROM orders AS o
#     INNER JOIN products AS p
#         ON o.product_id = p.product_id
#     WHERE o.status = 'Delivered'
#     GROUP BY p.category
# )
# SELECT
#     cr.category,
#     cr.total_revenue,
#     ct.target_revenue_inr,
#     ct.target_revenue_inr - cr.total_revenue AS variance,
#     ((cr.total_revenue - ct.target_revenue_inr) * 100.0)
#         / ct.target_revenue_inr AS percentage_variance,
#     CASE
#         WHEN cr.total_revenue >= ct.target_revenue_inr
#             THEN 'Above Target'
#         WHEN (ct.target_revenue_inr - cr.total_revenue)
#              <= (ct.target_revenue_inr * 0.15)
#             THEN 'Below Target - Watch'
#         ELSE 'Below Target - Critical'
#     END AS status
# FROM category_revenue AS cr
# INNER JOIN category_targets AS ct
#     ON cr.category = ct.category
# ORDER BY cr.category;

import sqlite3
import pandas as pd

conn = sqlite3.connect("bigbasket_capstone.db")

query = """
SELECT
    p.category AS category,
    strftime('%Y-%m', o.order_date) AS month,
    COUNT(o.order_id) AS order_count,
    SUM(o.amount_inr) AS total_revenue,
    AVG(o.amount_inr) AS avg_revenue
FROM orders AS o
INNER JOIN products AS p
    ON o.product_id = p.product_id
WHERE o.status = 'Delivered'
GROUP BY
    p.category,
    strftime('%Y-%m', o.order_date)
ORDER BY
    p.category,
    month;
"""

monthly_df = pd.read_sql(query, conn)
conn.close()

monthly_df.to_csv("monthly_category_revenue.csv", index=False)

print("Rows:", len(monthly_df))
print("Columns:", list(monthly_df.columns))
print("Grand Total Revenue:", monthly_df["total_revenue"].sum())
print("\nCSV created successfully.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ai_log.md
# # AI-Assisted Prompting Log
# 
# ## Prompt 1 — SQL Reporting Query
# 
# ### Role
# Act as a SQL analyst experienced with SQLite and retail/e-commerce reporting.
# 
# ### Context
# I am completing a BigBasket category performance diagnostic using a deterministic SQLite database containing products, customers, orders, and category revenue targets. The database contains 500 orders from January through June 2026.
# 
# ### Task
# Help me write a SQLite SQL query that joins orders with products, groups results by product category and month, and calculates order_count, total_revenue, and avg_revenue for Delivered orders only.
# 
# ### Constraints
# Use SQLite syntax. Use `strftime('%Y-%m', order_date)` for the month. Do not modify the underlying database. The output must contain exactly five columns: category, month, order_count, total_revenue, avg_revenue.
# 
# ### Format
# Return one runnable SQL query followed by a short explanation of the join, filtering, grouping, and date extraction.
# 
# ### Verification Performed
# I ran the SQL query against `bigbasket_capstone.db` in Google Colab. I verified that it returned exactly 36 rows, contained the five required columns, and produced a grand total Delivered revenue of INR 88,282. I also checked the category totals against the Part 1 SQL results.

from google.colab import files

part1_files = [
    "generate_data.py",
    "bigbasket_capstone.db",
    "orders_raw.csv",
    "products.csv",
    "verify.sql",
    "01_foundations.sql",
    "02_aggregation_joins.sql",
    "03_reporting.sql",
    "monthly_category_revenue.csv",
    "ai_log.md"
]

for f in part1_files:
    files.download(f)

import os
import zipfile

part1_files = [
    "generate_data.py",
    "bigbasket_capstone.db",
    "orders_raw.csv",
    "products.csv",
    "verify.sql",
    "01_foundations.sql",
    "02_aggregation_joins.sql",
    "03_reporting.sql",
    "monthly_category_revenue.csv",
    "ai_log.md"
]

# Check which files exist
print("Checking files...\n")

for f in part1_files:
    print("✅" if os.path.exists(f) else "❌", f)

# Create ZIP containing all files that exist
with zipfile.ZipFile("BigBasket_Part1_Files.zip", "w") as zipf:
    for f in part1_files:
        if os.path.exists(f):
            zipf.write(f)

print("\nZIP created successfully!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile verify.sql
# -- BigBasket Capstone Verification
# 
# -- Expected: 31
# SELECT COUNT(*) AS product_count FROM products;
# 
# -- Expected: 50
# SELECT COUNT(*) AS customer_count FROM customers;
# 
# -- Expected: 500
# SELECT COUNT(*) AS order_count FROM orders;
# 
# -- Expected: 6
# SELECT COUNT(*) AS category_target_count FROM category_targets;
# 
# -- Expected:
# -- Cancelled = 42
# -- Delivered = 434
# -- Pending = 24
# SELECT status, COUNT(*) AS status_count
# FROM orders
# GROUP BY status
# ORDER BY status;

import zipfile
import os

part1_files = [
    "generate_data.py",
    "bigbasket_capstone.db",
    "orders_raw.csv",
    "products.csv",
    "verify.sql",
    "01_foundations.sql",
    "02_aggregation_joins.sql",
    "03_reporting.sql",
    "monthly_category_revenue.csv",
    "ai_log.md"
]

with zipfile.ZipFile("BigBasket_Part1_Files.zip", "w") as zipf:
    for f in part1_files:
        zipf.write(f)

print("All 10 Part 1 files added successfully.")

from google.colab import files
files.download("BigBasket_Part1_Files.zip")

from google.colab import files
files.download("monthly_category_revenue.csv")